//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSR_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Needs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Needs()
        {
            this.NeedsReview = new HashSet<NeedsReview>();
        }
    
        public int ID { get; set; }
        public string Item { get; set; }
        public int Total_items { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public string Justification { get; set; }
        public string Comment { get; set; }
        public int id_Department { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeedsReview> NeedsReview { get; set; }
    }
}
