//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSR_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeedsReview
    {
        public int ID { get; set; }
        public int id_Need { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public int id_Document { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Needs Needs { get; set; }
    }
}
