//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSR_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSREntities : DbContext
    {
        public CSREntities()
            : base("name=CSREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Needs> Needs { get; set; }
        public virtual DbSet<NeedsReview> NeedsReview { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
